apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysql-pass
  literals:
  - password=train
resources:
  - provisioner.yaml
  - rbac.yaml
  - storage.yaml
  - mysql-dep.yaml
  - wp-dep.yaml
